# Generated by Django 3.1.6 on 2021-03-27 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('company_name', models.CharField(max_length=40)),
                ('days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_skipped', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Employee',
                'ordering': ['-salary'],
            },
        ),
    ]
